--

DROP TABLE IF EXISTS country;

CREATE TABLE country  (    
    id          int(15) NOT NULL,
    created     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    alpha_iso_2 char(2) NOT NULL,
    alpha_iso_3 char(3) NOT NULL,
    name        varchar(80) NOT NULL,
    name_es     varchar(80) NOT NULL,
    active      tinyint(15) NOT NULL DEFAULT '0',
    PRIMARY KEY(id)
)  ENGINE = InnoDB
   DEFAULT CHARSET = utf8mb4
   COLLATE = utf8mb4_unicode_ci;


-- country 
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (4,'AF','AFG','AFGHANISTAN','AFGANISTÁN',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (8,'AL','ALB','ALBANIA, PEOPLE''S SOCIALIST REPUBLIC OF','ALBANIA',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (10,'AQ','ATA','ANTARCTICA (THE TERRITORY SOUTH OF 60 DEG S)','ANTÁRTIDA',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (12,'DZ','DZA','ALGERIA, PEOPLE''S DEMOCRATIC REPUBLIC OF','ARGELIA',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (16,'AS','ASM','AMERICAN SAMOA','SAMOA AMERICANA',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (20,'AD','AND','ANDORRA, PRINCIPALITY OF','ANDORRA',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (24,'AO','AGO','ANGOLA, REPUBLIC OF','ANGOLA',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (28,'AG','ATG','ANTIGUA AND BARBUDA','ANTIGUA Y BARBUDA',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (31,'AZ','AZE','AZERBAIJAN, REPUBLIC OF','AZERBAIYAN',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (32,'AR','ARG','ARGENTINA, ARGENTINE REPUBLIC','ARGENTINA',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (36,'AU','AUS','AUSTRALIA, COMMONWEALTH OF','AUSTRALIA',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (40,'AT','AUT','AUSTRIA, REPUBLIC OF','AUSTRIA',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (44,'BS','BHS','BAHAMAS, COMMONWEALTH OF THE','BAHAMAS ',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (48,'BH','BHR','BAHRAIN, KINGDOM OF','BAHRÉIN',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (50,'BD','BGD','BANGLADESH, PEOPLE''S REPUBLIC OF','BANGLADESH',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (51,'AM','ARM','ARMENIA','ARMENIA',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (52,'BB','BRB','BARBADOS','BARBADOS ',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (56,'BE','BEL','BELGIUM, KINGDOM OF','BÉLGICA',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (60,'BM','BMU','BERMUDA','BERMUDAS',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (64,'BT','BTN','BHUTAN, KINGDOM OF','BUTÁN',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (68,'BO','BOL','BOLIVIA, REPUBLIC OF','BOLIVIA',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (70,'BA','BIH','BOSNIA AND HERZEGOVINA','BOSNIA Y HERZEGOVINA',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (72,'BW','BWA','BOTSWANA, REPUBLIC OF','BOTSUANA',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (74,'BV','BVT','BOUVET ISLAND (BOUVETOYA)','ISLA BOUVET',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (76,'BR','BRA','BRAZIL, FEDERATIVE REPUBLIC OF','BRASIL',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (84,'BZ','BLZ','BELIZE','BELICE',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (86,'IO','IOT','BRITISH INDIAN OCEAN TERRITORY (CHAGOS ARCHIPELAGO)','TERRITORIO BRITÁNICO DEL OCÉANO ÍNDICO',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (90,'SB','SLB','SOLOMON ISLANDS','ISLAS SALOMÓN',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (92,'VG','VGB','BRITISH VIRGIN ISLANDS','ISLAS VÍRGENES BRITANICAS',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (96,'BN','BRN','BRUNEI DARUSSALAM','BRUNÉI',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (100,'BG','BGR','BULGARIA, PEOPLE''S REPUBLIC OF','BULGARIA',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (104,'MM','MMR','MYANMAR','',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (108,'BI','BDI','BURUNDI, REPUBLIC OF','BURUNDI',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (112,'BY','BLR','BELARUS','BIELORRUSIA',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (116,'KH','KHM','CAMBODIA, KINGDOM OF','CAMBOYA',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (120,'CM','CMR','CAMEROON, UNITED REPUBLIC OF','CAMERÚN',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (124,'CA','CAN','CANADA','CANADÁ',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (128,'CT','CTE','CANTON & ENDERBURY ISLANDS','',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (132,'CV','CPV','CAPE VERDE, REPUBLIC OF','CABO VERDE',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (136,'KY','CYM','CAYMAN ISLANDS','ISLAS CAIMÁN',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (140,'CF','CAF','CENTRAL AFRICAN REPUBLIC','REPÚBLICA CENTROAFRICANA',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (144,'LK','LKA','SRI LANKA, DEMOCRATIC SOCIALIST REPUBLIC OF','SRI LANKA',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (148,'TD','TCD','CHAD, REPUBLIC OF','CHAD',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (152,'CL','CHL','CHILE, REPUBLIC OF','CHILE',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (156,'CN','CHN','CHINA, PEOPLE''S REPUBLIC OF','CHINA',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (158,'TW','TWN','TAIWAN, PROVINCE OF CHINA','TAIWAN',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (162,'CX','CXR','CHRISTMAS ISLAND','ISLA DE NAVIDAD',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (166,'CC','CCK','COCOS (KEELING) ISLANDS','ISLAS COCOS',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (170,'CO','COL','COLOMBIA, REPUBLIC OF','COLOMBIA',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (174,'KM','COM','COMOROS, UNION OF THE','COMORAS',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (175,'YT','MYT','MAYOTTE','MAYOTTE',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (178,'CG','COG','CONGO, PEOPLE''S REPUBLIC OF','REPÚBLICA DEL CONGO',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (180,'CD','COD','CONGO, DEMOCRATIC REPUBLIC OF','REPÚBLICA DEMOCRÁTICA DEL CONGO',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (184,'CK','COK','COOK ISLANDS','ISLAS COOK',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (188,'CR','CRI','COSTA RICA, REPUBLIC OF','COSTA RICA',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (191,'HR','HRV','HRVATSKA (CROATIA)','CROACIA',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (192,'CU','CUB','CUBA, REPUBLIC OF','CUBA ',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (196,'CY','CYP','CYPRUS, REPUBLIC OF','CHIPRE',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (200,'CS','CSK','CZECHOSLOVAKIA, CZECHOSLOVAK SOCIALIST REPUBLIC','REPÚBLICA SOCIALISTA CHECOSLOVACA',0);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (203,'CZ','CZE','CZECH REPUBLIC','REPÚBLICA CHECA',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (204,'BJ','BEN','BENIN, PEOPLE''S REPUBLIC OF','BENÍN',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (208,'DK','DNK','DENMARK, KINGDOM OF','DINAMARCA',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (212,'DM','DMA','DOMINICA, COMMONWEALTH OF','DOMINICA',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (214,'DO','DOM','DOMINICAN REPUBLIC','REPÚBLICA DOMINICANA',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (216,'NQ','ATN','DRONNING MAUD LAND','',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (218,'EC','ECU','ECUADOR, REPUBLIC OF','ECUADOR',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (222,'SV','SLV','EL SALVADOR, REPUBLIC OF','EL SALVADOR',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (226,'GQ','GNQ','EQUATORIAL GUINEA, REPUBLIC OF','GUINEA ECUATORIAL',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (230,'ET','ETH','ETHIOPIA','ETIOPÍA',0);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (231,'ET','ETH','ETHIOPIA','ETIOPÍA',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (232,'ER','ERI','ERITREA','ERITREA',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (233,'EE','EST','ESTONIA','ESTONIA',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (234,'FO','FRO','FAEROE ISLANDS','ISLAS FEROE',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (238,'FK','FLK','FALKLAND ISLANDS (MALVINAS)','ISLAS MALVINAS',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (239,'GS','SGS','SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS','ISLAS GEORGIAS DEL SUR Y SANDWICH DEL SUR',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (242,'FJ','FJI','FIJI, REPUBLIC OF THE FIJI ISLANDS','FIYI',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (246,'FI','FIN','FINLAND, REPUBLIC OF','FINLANDIA',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (249,'FX','FXX','FRANCE, METROPOLITAN','FRANCE, METROPOLITAN',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (250,'FR','FRA','FRANCE, FRENCH REPUBLIC','REPÚBLICA DE FRANCIA',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (254,'GF','GUF','FRENCH GUIANA','GUAYANA FRANCESA',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (258,'PF','PYF','FRENCH POLYNESIA','POLINESIA FRANCESA',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (260,'TF','ATF','FRENCH SOUTHERN TERRITORIES','TERRITORIOS AUSTRALES FRANCESES',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (262,'DJ','DJI','DJIBOUTI, REPUBLIC OF','YIBUTI',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (266,'GA','GAB','GABON, GABONESE REPUBLIC','GABÓN',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (268,'GE','GEO','GEORGIA','GEORGIA',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (270,'GM','GMB','GAMBIA, REPUBLIC OF THE','GAMBIA',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (275,'PS','PSE','PALESTINIAN TERRITORY, OCCUPIED','PALESTINA',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (276,'DE','DEU','GERMANY','ALEMANIA',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (278,'DD','DDR','GERMAN DEMOCRATIC REPUBLIC','REPÚBLICA DEMOCRÁTICA DE ALEMANIA',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (280,'DE','DEU','GERMANY, FEDERAL REPUBLIC OF','REPÚBLICA FEDERAL DE ALEMANIA',0);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (288,'GH','GHA','GHANA, REPUBLIC OF','GHANA',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (292,'GI','GIB','GIBRALTAR','GIBRALTAR',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (296,'KI','KIR','KIRIBATI, REPUBLIC OF','KIRIBATI',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (300,'GR','GRC','GREECE, HELLENIC REPUBLIC','GRECIA',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (304,'GL','GRL','GREENLAND','GROENLANDIA',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (308,'GD','GRD','GRENADA','GRANADA ',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (312,'GP','GLP','GUADALOUPE','GUADALUPE',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (316,'GU','GUM','GUAM','GUAM',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (320,'GT','GTM','GUATEMALA, REPUBLIC OF','GUATEMALA',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (324,'GN','GIN','GUINEA, REVOLUTIONARY PEOPLE''S REP''C OF','GUINEA',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (328,'GY','GUY','GUYANA, REPUBLIC OF','GUYANA',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (332,'HT','HTI','HAITI, REPUBLIC OF','HAITÍ ',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (334,'HM','HMD','HEARD AND MCDONALD ISLANDS','ISLAS HEARD Y MCDONALD',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (336,'VA','VAT','HOLY SEE (VATICAN CITY STATE)','CIUDAD DEL VATICANO',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (340,'HN','HND','HONDURAS, REPUBLIC OF','HONDURAS',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (344,'HK','HKG','HONG KONG, SPECIAL ADMINISTRATIVE REGION OF CHINA','HONG KONG',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (348,'HU','HUN','HUNGARY, HUNGARIAN PEOPLE''S REPUBLIC','HUNGRÍA',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (352,'IS','ISL','ICELAND, REPUBLIC OF','ISLANDIA',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (356,'IN','IND','INDIA, REPUBLIC OF','REPÚBLICA DE INDIA',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (360,'ID','IDN','INDONESIA, REPUBLIC OF','INDONESIA',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (364,'IR','IRN','IRAN, ISLAMIC REPUBLIC OF','IRÁN',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (368,'IQ','IRQ','IRAQ, REPUBLIC OF','IRAQ',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (372,'IE','IRL','IRELAND','IRLANDA',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (376,'IL','ISR','ISRAEL, STATE OF','ISRAEL',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (380,'IT','ITA','ITALY, ITALIAN REPUBLIC','ITALIA',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (384,'CI','CIV','COTE D''IVOIRE, IVORY COAST, REPUBLIC OF THE','COSTA DE MARFIL',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (388,'JM','JAM','JAMAICA','JAMAICA ',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (392,'JP','JPN','JAPAN','JAPÓN',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (396,'JT','JTN','JOHNSTON ISLAND','ISLAS JOHNSTON',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (398,'KZ','KAZ','KAZAKHSTAN, REPUBLIC OF','KAZAJISTÁN',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (400,'JO','JOR','JORDAN, HASHEMITE KINGDOM OF','JORDANIA',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (404,'KE','KEN','KENYA, REPUBLIC OF','KENIA',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (408,'KP','PRK','KOREA, DEMOCRATIC PEOPLE''S REPUBLIC OF','COREA DEL NORTE',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (410,'KR','KOR','KOREA, REPUBLIC OF','COREA DEL SUR',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (414,'KW','KWT','KUWAIT, STATE OF','KUWAIT',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (417,'KG','KGZ','KYRGYZ REPUBLIC','KIRGUISTÁN',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (418,'LA','LAO','LAO PEOPLE''S DEMOCRATIC REPUBLIC','LAOS',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (422,'LB','LBN','LEBANON, LEBANESE REPUBLIC','LIBANO',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (426,'LS','LSO','LESOTHO, KINGDOM OF','LESOTO',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (428,'LV','LVA','LATVIA','LETONIA',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (430,'LR','LBR','LIBERIA, REPUBLIC OF','LIBERIA',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (434,'LY','LBY','LIBYAN ARAB JAMAHIRIYA','LIBIA',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (438,'LI','LIE','LIECHTENSTEIN, PRINCIPALITY OF','LIECHTENSTEIN',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (440,'LT','LTU','LITHUANIA','LITUANIA',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (442,'LU','LUX','LUXEMBOURG, GRAND DUCHY OF','LUXEMBURGO',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (446,'MO','MAC','MACAO, SPECIAL ADMINISTRATIVE REGION OF CHINA','MACAO',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (450,'MG','MDG','MADAGASCAR, REPUBLIC OF','MADAGASCAR',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (454,'MW','MWI','MALAWI, REPUBLIC OF','MALAWI',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (458,'MY','MYS','MALAYSIA','MALASIA',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (462,'MV','MDV','MALDIVES, REPUBLIC OF','MALDIVAS',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (466,'ML','MLI','MALI, REPUBLIC OF','MALÍ',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (470,'MT','MLT','MALTA, REPUBLIC OF','MALTA',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (474,'MQ','MTQ','MARTINIQUE','MARTINICA',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (478,'MR','MRT','MAURITANIA, ISLAMIC REPUBLIC OF','MAURITANIA',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (480,'MU','MUS','MAURITIUS','MAURICIO',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (484,'MX','MEX','MEXICO, UNITED MEXICAN STATES','ESTADOS UNIDOS MEXICANOS',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (488,'MI','MID','MIDWAY ISLANDS','ISLAS MIDWAY',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (492,'MC','MCO','MONACO, PRINCIPALITY OF','MÓNACO',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (496,'MN','MNG','MONGOLIA, MONGOLIAN PEOPLE''S REPUBLIC','MONGOLIA',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (498,'MD','MDA','MOLDOVA, REPUBLIC OF','MOLDAVIA',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (500,'MS','MSR','MONTSERRAT','MONSERRAT',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (504,'MA','MAR','MOROCCO, KINGDOM OF','MARRUECOS',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (508,'MZ','MOZ','MOZAMBIQUE, PEOPLE''S REPUBLIC OF','MOZAMBIQUE',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (512,'OM','OMN','OMAN, SULTANATE OF','OMÁN',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (516,'NA','NAM','NAMIBIA','NAMIBIA',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (520,'NR','NRU','NAURU, REPUBLIC OF','NAURU',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (524,'NP','NPL','NEPAL, KINGDOM OF','NEPAL',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (528,'NL','NLD','NETHERLANDS, KINGDOM OF THE','REINO DE HOLANDA',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (530,'AN','ANT','NETHERLANDS ANTILLES','ANTILLAS NEERLANDESAS',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (532,'AN','ANT','NETHERLANDS ANTILLES','ANTILLAS HOLANDESAS',0);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (533,'AW','ABW','ARUBA','ARUBA',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (536,'NT','NTZ','NEUTRAL ZONE','',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (540,'NC','NCL','NEW CALEDONIA','NUEVA CALEDONIA',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (548,'VU','VUT','VANUATU','VANUATU',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (554,'NZ','NZL','NEW ZEALAND','NUEVA ZELANDA',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (558,'NI','NIC','NICARAGUA, REPUBLIC OF','REPUBLICA DE NICARAGUA',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (562,'NE','NER','NIGER, REPUBLIC OF THE','NÍGER',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (566,'NG','NGA','NIGERIA, FEDERAL REPUBLIC OF','NIGERIA',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (570,'NU','NIU','NIUE, REPUBLIC OF','NIUE',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (574,'NF','NFK','NORFOLK ISLAND','NORFOLK',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (578,'NO','NOR','NORWAY, KINGDOM OF','NORUEGA',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (580,'MP','MNP','NORTHERN MARIANA ISLANDS','ISLAS MARIANAS DEL NORTE',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (581,'UM','UMI','UNITED STATES MINOR OUTLYING ISLANDS','ISLAS ULTRAMARINAS DE ESTADOS UNIDOS',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (582,'PC','PCI','PACIFIC ISLANDS (TRUST TERRITORY)','ISLAS PACIFICAS',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (583,'FM','FSM','MICRONESIA, FEDERATED STATES OF','MICRONESIA',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (584,'MH','MHL','MARSHALL ISLANDS','ISLAS MARSHALL',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (585,'PW','PLW','PALAU','PALAOS',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (586,'PK','PAK','PAKISTAN, ISLAMIC REPUBLIC OF','PAKISTÁN',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (590,'PA','PAN','PANAMA, REPUBLIC OF','REPÚBLICA DE PANAMÁ',0);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (591,'PA','PAN','PANAMA, REPUBLIC OF','REPÚBLICA DE PANAMÁ',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (598,'PG','PNG','PAPUA NEW GUINEA','PAPÚA NUEVA GUINEA',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (600,'PY','PRY','PARAGUAY, REPUBLIC OF','PARAGUAY',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (604,'PE','PER','PERU, REPUBLIC OF','PERÚ',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (608,'PH','PHL','PHILIPPINES, REPUBLIC OF THE','FILIPINAS',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (612,'PN','PCN','PITCAIRN ISLAND','ISLAS PITCAIRN',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (616,'PL','POL','POLAND, POLISH PEOPLE''S REPUBLIC','POLONIA',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (620,'PT','PRT','PORTUGAL, PORTUGUESE REPUBLIC','PORTUGAL',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (624,'GW','GNB','GUINEA-BISSAU, REPUBLIC OF','GUINEA-BISSAU',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (626,'TL','TLS','TIMOR-LESTE, DEMOCRATIC REPUBLIC OF','TIMOR ORIENTAL',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (630,'PR','PRI','PUERTO RICO','PUERTO RICO',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (634,'QA','QAT','QATAR, STATE OF','QATAR',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (638,'RE','REU','REUNION','REUNIÓN',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (642,'RO','ROU','ROMANIA, SOCIALIST REPUBLIC OF','RUMANIA',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (643,'RU','RUS','RUSSIAN FEDERATION','RUSIA',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (646,'RW','RWA','RWANDA, RWANDESE REPUBLIC','RUANDA',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (654,'SH','SHN','ST. HELENA','SANTA HELENA',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (658,'KN','KNA','ST. KITTS-NEVIS-ANGUILLA','',0);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (659,'KN','KNA','ST. KITTS AND NEVIS','SAN CRISTÓBAL Y NIEVES',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (660,'AI','AIA','ANGUILLA','ANGUILA',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (662,'LC','LCA','ST. LUCIA','SANTA LUCIA',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (666,'PM','SPM','ST. PIERRE AND MIQUELON','SAN PEDRO Y MIQUELÓN',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (670,'VC','VCT','ST. VINCENT AND THE GRENADINES','SAN VICENTE Y LAS GRANADINAS',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (674,'SM','SMR','SAN MARINO, REPUBLIC OF','SAN MARINO',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (678,'ST','STP','SAO TOME AND PRINCIPE, DEMOCRATIC REPUBLIC OF','SANTO TOMÉ Y PRÍNCIPE',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (682,'SA','SAU','SAUDI ARABIA, KINGDOM OF','ARABIA SAUDITA',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (686,'SN','SEN','SENEGAL, REPUBLIC OF','SENEGAL',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (690,'SC','SYC','SEYCHELLES, REPUBLIC OF','SEYCHELLES',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (694,'SL','SLE','SIERRA LEONE, REPUBLIC OF','SIERRA LEONA',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (702,'SG','SGP','SINGAPORE, REPUBLIC OF','SINGAPUR',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (703,'SK','SVK','SLOVAKIA (SLOVAK REPUBLIC)','REPÚBLICA DE ESLOVAQUIA',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (704,'VN','VNM','VIET NAM, SOCIALIST REPUBLIC OF','VIETNAM',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (705,'SI','SVN','SLOVENIA','ESLOVENIA',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (706,'SO','SOM','SOMALIA, SOMALI REPUBLIC','SOMALIA',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (710,'ZA','ZAF','SOUTH AFRICA, REPUBLIC OF','SUDÁFRICA',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (716,'ZW','ZWE','ZIMBABWE','ZIMBAWE DEL NORTE',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (720,'YD','YMD','YEMEN, DEMOCRATIC, PEOPLE''S DEMOCRATIC REPUBLIC OF','YEMEN',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (724,'ES','ESP','SPAIN, SPANISH STATE','ESPAÑA',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (732,'EH','ESH','WESTERN SAHARA','SAHARA OCCIDENTAL',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (736,'SD','SDN','SUDAN, DEMOCRATIC REPUBLIC OF THE','SUDÁN',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (740,'SR','SUR','SURINAME, REPUBLIC OF','SURINAM',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (744,'SJ','SJM','SVALBARD & JAN MAYEN ISLANDS','SVALBARD Y JAN MAYEN',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (748,'SZ','SWZ','SWAZILAND, KINGDOM OF','SUAZILANDIA',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (752,'SE','SWE','SWEDEN, KINGDOM OF','SUECIA',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (756,'CH','CHE','SWITZERLAND, SWISS CONFEDERATION','SUIZA',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (760,'SY','SYR','SYRIAN ARAB REPUBLIC','SIRIA',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (762,'TJ','TJK','TAJIKISTAN','TAYIKISTÁN',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (764,'TH','THA','THAILAND, KINGDOM OF','TAILANDIA',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (768,'TG','TGO','TOGO, TOGOLESE REPUBLIC','TOGO',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (772,'TK','TKL','TOKELAU (TOKELAU ISLANDS)','TOKELAU',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (776,'TO','TON','TONGA, KINGDOM OF','TONGA',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (780,'TT','TTO','TRINIDAD AND TOBAGO, REPUBLIC OF','TRINIDAD Y TOBAGO',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (784,'AE','ARE','UNITED ARAB EMIRATES','EMIRÁTOS ÁRABES UNIDOS',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (788,'TN','TUN','TUNISIA, REPUBLIC OF','TÚNEZ',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (792,'TR','TUR','TURKEY, REPUBLIC OF','TURQÚIA',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (795,'TM','TKM','TURKMENISTAN','TURKMENISTÁN',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (796,'TC','TCA','TURKS AND CAICOS ISLANDS','ISLAS TURCAS Y CAICOS',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (798,'TV','TUV','TUVALU','TUVALU',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (800,'UG','UGA','UGANDA, REPUBLIC OF','UGANDA',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (804,'UA','UKR','UKRAINE','UCRANIA',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (807,'MK','MKD','MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF','MACEDONIA (ARY)',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (810,'SU','SUN','USSR, UNION OF SOVIET SOCIALIST REPUBLICS','UNIÓN DE REPÚBLICAS SOCIALISTAS SOVIÉTICA',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (818,'EG','EGY','EGYPT, ARAB REPUBLIC OF','EGIPTO ',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (826,'GB','GBR','UNITED KINGDOM OF GREAT BRITAIN & N. IRELAND','REINO UNIDO DE GRAN BRETAÑA E IRLANDA',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (834,'TZ','TZA','TANZANIA, UNITED REPUBLIC OF','REPÚBLICA UNIDA DE TANZANIA',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (840,'US','USA','UNITED STATES OF AMERICA','ESTADOS UNIDOS DE AMÉRICA',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (849,'PU','PUS','US MISCELLANEOUS PACIFIC ISLANDS','',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (850,'VI','VIR','US VIRGIN ISLANDS','ISLAS VÍRGENES ESTADUNIDENSES',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (854,'BF','BFA','BURKINA FASO','BURKINA FASO',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (858,'UY','URY','URUGUAY, EASTERN REPUBLIC OF','URUGUAY',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (860,'UZ','UZB','UZBEKISTAN','UZBEKISTÁN',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (862,'VE','VEN','VENEZUELA, BOLIVARIAN REPUBLIC OF','REPÚBLICA BOLIVARIANA DE VENEZUELA',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (872,'WK','WAK','WAKE ISLAND','',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (876,'WF','WLF','WALLIS AND FUTUNA ISLANDS','WALLIS Y FUTUNA',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (882,'WS','WSM','SAMOA, INDEPENDENT STATE OF','SAMOA  ',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (886,'YE','YEM','YEMEN, YEMEN ARAB REPUBLIC','YEMEN',0);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (887,'YE','YEM','YEMEN','YEMEN',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (890,'YU','YUG','YUGOSLAVIA, SOCIALIST FEDERAL REPUBLIC OF','YUGOSLAVIA',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (891,'CS','SCG','SERBIA AND MONTENEGRO','YUGOSLAVIA',1);
INSERT INTO country (id, alpha_iso_2, alpha_iso_3, name, name_es, active) VALUES (894,'ZM','ZMB','ZAMBIA, REPUBLIC OF','ZAMBIA',1);
